### ISSUE TITLE
When applying a steady-state probe, it should be "steady-state" not "steady" as currently reported

### ISSUE THREAD

**Issue by russmiles** [chaostoolkit/chaostoolkit#1]
When you run an experiment the logging mentions that a `steady` probe is being applied. This should probably be renamed a `steady-state` probe, and might just be a name change in the experimental method.

See the following output for where this occurs when running the `service-down-not-visible-to-users sample` experiment:

```
[I 170930 14:01:15 plan:134]  Applying steady probe 'microservices-all-healthy'
```

**Comment by russmiles** [comment]
Have confirmed that the toolkit itself will need to change to support `steady-state` instead of `steady` probe nomenclature.

**Comment by russmiles** [comment]
Should probably incorporate moving to `close-state` instead of `close` too

**Comment by Lawouach** [comment]
Should be updated in 0.2.4
