### ISSUE TITLE
Question: How to check Steady State Hypothesis correctly?

### ISSUE THREAD

**Issue by mkaszub** [chaostoolkit/chaostoolkit#103]
Let's imagine that our experiment is doing following actions
- stressing cpus
- repeatedly restarting machine

All those methods/actions have one thing in common: they last as long as "action" is running. 

So our full experiment could look like that:
- Steady State Hypothesis: check if ok
- Methods:
    - stressing cpus
    - repeatedly restarting machine
    - switching on and off network ports
- Steady State Hypothesis: check if ok

As this experiment is valid and possible to write with current stack one thing is missing for me. 

What if I want to stress cpu and in the same time check Steady State Hypothesis. When I use action like stop_machine, machine is stopped while checking Steady State Hypothesis. This is not the case for actions that change state of the system only while running.

We cannot use "background" switch as we are waiting for all actions before running final Steady State Hypothesis. I could implement action in the way that it run command in a thread and exit immediately. But somehow this is not very appealing to me :)  

Do I get it right? What are your advices? 

Regards,
Marcin

**Comment by Lawouach** [comment]
Hi @mkaszub,

I am so sorry I haven't at least acknowledged your question. Time flies :(

Your request is indeed becoming quite common, folks want to play the SSH while running the method. [This issue](https://github.com/chaostoolkit/chaostoolkit/issues/104) seems to cover the discussion and I would be happy to know if you see a more appealing solution in what is mentioned there.

Cheers,

**Comment by mkaszub** [comment]
Proposed solution with continious SSH mode looks good to me and would solve my issues.
