### ISSUE TITLE
Add Grafana Probe

### ISSUE THREAD

**Issue by amerghazal** [chaostoolkit/chaostoolkit#106]
We have a use-case whereby pulling Grafana snapshots for graphs and reporting state changes in alerts during an experiment would be useful. I'd be happy to contribute this but wanted to see if this had been considered previously and whether or not issues have been identified. Many thanks!

**Comment by russmiles** [comment]
This sounds like a great idea, and would probably require a new extension project in the incubator https://github.com/chaostoolkit-incubator

I can create that repo and its baseline contents if this is something ready to be worked upon?

**Comment by amerghazal** [comment]
Thanks for the quick reply. Sounds good! No rush; I should be ready to work on it in a few days.

**Comment by Lawouach** [comment]
Hello folks,

I wonder @amerghazal if you're still up for that extension as I can see its benefit for sure :)

**Comment by amerghazal** [comment]
@Lawouach I'm definitely still up for it. I had gotten distracted but will be available to work on it this coming week.
