### ISSUE TITLE
Unable to join Slack Channel

### ISSUE THREAD

**Issue by museadmin** [chaostoolkit/chaostoolkit#110]
Can you please fix the link to the join page for the slack channel. It is incredibly frustrating not to be able to discuss the Chaos Toolkit with anyone.

For several weeks now the page has presented a form to enter your email address and then submit the request to join. At which point it would report a "expired token" and nothing more would happen.

Now the page is just coming up as a black blank page.

your link to this page points to https://join.chaostoolkit.org/ 

Is this the correct page?

**Comment by Lawouach** [comment]
Thank you so much @museadmin. This totally went under our radar. This is now fixed (as best as I could say).
