### ISSUE TITLE
Validation could/should check if the experiment can actually run

### ISSUE THREAD

**Issue by Lawouach** [chaostoolkit/chaostoolkit#112]
Currently, the validation only looks at the syntax of the experiment. It's helpful but doesn't tell us if the experiment is actually in a position to actually run.

Maybe we could perform some lookup of the system and ask if it's under the right conditions to be experimented on.

**Comment by russmiles** [comment]
Although of course this check would only be correct at the specific moment that validation is run. If there was (any) delay between validation and `chaos run` then the possibility would be that the system was now in a state where that validation might have failed?

**Comment by Lawouach** [comment]
Exactly, this cannot be a promise per se.
