### ISSUE TITLE
Failing action should fail experiment

### ISSUE THREAD

**Issue by rogerhmar** [chaostoolkit/chaostoolkit#115]
I have set up the following experiment:
```json
{
    "version": "1.0.0",
    "title": "Memory leak",
    "description": "We shold be able to have a memoryleak in a pod",
    "tags": [
        "basecase"
    ],
    "steady-state-hypothesis": {
        "title": "All deployments are OK",
        "probes": [
            {
                "type": "probe",
                "tolerance": true,
                "provider": {
                  "type": "python",
                  "module": "chaosk8s.probes",
                  "func": "all_microservices_healthy"
                },
                "name": "all-microservices-healthy"
            }
        ]
    },
    "method": [
        {
            "type": "action",
            "provider": {
              "type": "python",
              "module": "chaosk8s.actions",
              "arguments": {
                "spec_path": "./memleak-deployment.yaml"
              },
              "func": "start_microservice"
            },
            "name": "start-microservice"
        }
    ],
    "rollbacks": [
        {
            "type": "action",
            "provider": {
              "type": "python",
              "module": "chaosk8s.actions",
              "arguments": {
                "name": "memory-leak"
              },
              "func": "kill_microservice"
            },
            "name": "kill-microservice"
          }
    ]
}```
For some reason reason, I get a failure in the "start_microservice" action (but that is a separate issue). The problem is that the experiment does not fail:

![image](https://user-images.githubusercontent.com/1544931/60712491-71927a80-9f17-11e9-95c5-0ea87b73cd94.png)


I expect it to fail, and it is important that it does.

**Comment by Lawouach** [comment]
Hello @rogerhmar 

It's a tricky one but it comes so often that we need to address it.

The nature of an experiment is that it tries to mimic conditions that could happen, including the domino effect and side-effects of side-effects. The Chaos Toolkit takes the approach that a method must run its course and we see how the system was impacted. Afterall, sometimes you do learn that even under duress your initial condition remained. It's a positive piece of learning.

However, [others have asked](https://github.com/chaostoolkit/chaostoolkit/issues/104) for a quick bail out in cases like yours, we call that the test mode. Currently, there is no such mode implemented natively in the core of the toolkit. I need to look how to achieve that cleanly.

Meanwhile, one way of doing this is with a [control](https://docs.chaostoolkit.org/reference/extending/create-control-extension/).

A control is another function that runs before/after each action/probe (or even more globally). A control has a mechanism to [interrupt the whole experiment](https://docs.chaostoolkit.org/reference/extending/create-control-extension/#interruptinng-the-execution) based on the condition you want.

Hopefully, this may help for now?

**Comment by rogerhmar** [comment]
Thank you for the quick response. I am a bit new to Chaos Engineering, so I might be a bit of target. I do not think that it is very important to abort the experiment. For me that is more a nice to have feature for optimizing time usage. As long as I tidy up in the "tear down" that is no issue. 

What I am talking about here is that the experiment conclusion should be "Failed" (or False) when one or more steps are failing, since the conditions for the experiment is not fullfilled. At least is should be set as "Inconclusive". H0 is not verified nor falsified - Potentially nothing has happend.

**Comment by Lawouach** [comment]
I think there is some truth in that last statement. The trick is to define "failing condition" though. Is it failing because the system is broken? Is it failing because the action doesn't work as it should (like buggy input...)?

How to evaluate the action is working in the expected boundaries from when it actually misbehaves?

I find that discussion quite exciting to be honest and it fits some larger discussion around taking the whole chaos experiment further via the Open Chaos project (https://openchaos.io/).

I'll cc @russmiles on this one.
