### ISSUE TITLE
Add --ignore-config option to chaos validate

### ISSUE THREAD

**Issue by russmiles** [chaostoolkit/chaostoolkit#117]
Currently `chaos validate` seems to stop at the first validation error, which is frequently a reference to a configuration variable that hasn't been set. This can sometimes mean that you end up having to set up the environment variables when you have no intention of running the experiment, just to get past this point.

It'd be great if there was a `--ignore-config` or `--no-env-validation` option that turned this aspect off.

**Comment by pravarag** [comment]
@russmiles if someone is not already working on this, I would like to take up on it.

**Comment by russmiles** [comment]
I’m not aware of it being in fight @pravarag ; @lawaouch seems a nice one to work on?

**Comment by russmiles** [comment]
Wdyt @Lawouach ?

**Comment by Lawouach** [comment]
Maybe something like:

```
--ignore FILTER
```

where FILTER could be more expressive than a flag per section.

wdyt?

**Comment by pravarag** [comment]
@Lawouach is this change already in progress as part of any other enhancement? Otherwise I can take up on it.

**Comment by Lawouach** [comment]
Hi @pravarag please have a try indeed :) Thank you!

**Comment by russmiles** [comment]
@pravarag did you have any luck with progressing this issue?
