### ISSUE TITLE
Formatting of chaostoolkit output

### ISSUE THREAD

**Issue by grubert65** [chaostoolkit/chaostoolkit#120]
It would be nice to be able to change the default formatting of the chaostoolkit output. In our NFT pipeline all processes outputs encoded in JSON are automatically collected by Logstash and ELK, so to be easily searchable through Kibana. Currently the output format is fixed and hardcoded though it should be possible and not that difficult to parse a formatting string from the profile and have the chance to change it. Currently we just implemented a small script piped to the chaos command to solve this.

**Comment by Lawouach** [comment]
Hi there @grubert65 
You are correct, this should be a good improvement.

**Comment by Lawouach** [comment]
Hey @grubert65, I'm looking into this one today as per #122.

**Comment by Lawouach** [comment]
I wonder if you could look at #76 and see if that looks useful to you?

**Comment by grubert65** [comment]
Hi Sylvain,
yes I will, sounds addressing what I was looking for.
Best,
Marco.

Il giorno lun 12 ago 2019 alle ore 07:37 Sylvain Hellegouarch <
notifications@github.com> ha scritto:
