### ISSUE TITLE
pauses with Number var

### ISSUE THREAD

**Issue by racer78** [chaostoolkit/chaostoolkit#123]
I try to run an experiment with variables configured in "configuration"
`"configuration":{ "waitTime": 3 }`
There it´s defined as Number
Then I want to use this var in pauses

`"pauses":{ "after": "${waitTime}"}`

This results into an error that pauses needs a Number
Can it be fixed that variables can be uses also in "pauses" ?

**Comment by Lawouach** [comment]
Hello @racer78 

A very good point. It's because we don't consider pause values as variables, they can't be parametarized. Maybe they should, or at least the doc should be clearer.

So for now, you are a bit of out luck on that one I'm afraid :(

**Comment by racer78** [comment]
Thanks for the fast answer.
But won´t this affect  also other situations like activities with http requests where in json Int or Float values are required?
e.g.` "configuration":{ "waitTime": 3 }`  is correctly defined as Number but converted to a string when requesting the var as `"${waitTime}"`

**Comment by Lawouach** [comment]
Indeed. There is an issue that was raised along these lines https://github.com/chaostoolkit-incubator/community-playground/issues/25

The trick is simplicity vs expressiveness. We wouldn't known if the value is meant to be a number of something else. Mind you, now that I think of it, I guess we could make the call that, when it's not a string, it's a number.

The other difficulty is that `"configuration":{ "waitTime": ${waitTime} }` is not a valid json expression.

**Comment by dellekappa** [comment]
I'm facing the same issue of @dav1dc-pcf.
Are there some news about it?
