### ISSUE TITLE
Seeing different behaviour between `chaos validate` and `chaos run` when based on a URL

### ISSUE THREAD

**Issue by russmiles** [chaostoolkit/chaostoolkit#127]
When I run `chaos run` with a valid URL to a experiment resource on GitHub I get the following:

```
export APPLICATION_ENTRYPOINT_URL=http://192.168.99.100:32474; 
            export SERVICE_NAME=my-service; \
                   chaos run https://raw.githubusercontent.com/open-chaos/experiment-catalog/master/kubernetes/kill_microservice/kill_microservice.json
[2019-09-27 10:52:35 INFO] Validating the experiment's syntax
[2019-09-27 10:52:35 ERROR] could not find Python module 'chaosk8s.actions' in activity 'kill-microservice'
```

That is entirely fine, as the experiment appears to be being downloaded and the complaint that I don't have the Kubernetes extension in this virtual environment is sound.

However when I do the same with `chaos validate` I get a different output:

```
export APPLICATION_ENTRYPOINT_URL=http://192.168.99.100:32474; \
            export SERVICE_NAME=my-service; \
                   chaos validate https://raw.githubusercontent.com/open-chaos/experiment-catalog/master/kubernetes/kill_microservice/kill_microservice.json
Usage: chaos validate [OPTIONS] PATH
Try "chaos validate --help" for help.

Error: Invalid value for "PATH": Path "https://raw.githubusercontent.com/open-chaos/experiment-catalog/master/kubernetes/kill_microservice/kill_microservice.json" does not exist.
```

This feels like the toolkit can't access the resource?

**Comment by russmiles** [comment]
Ahh, it looks like `validate` may not have the same support for "from a URL", see https://github.com/chaostoolkit/chaostoolkit/blob/7c42b72172677b1c3b7e662c23705e413f62f73d/chaostoolkit/cli.py#L151

**Comment by russmiles** [comment]
As opposed to the description on `chaos run`, see https://github.com/chaostoolkit/chaostoolkit/blob/7c42b72172677b1c3b7e662c23705e413f62f73d/chaostoolkit/cli.py#L97

**Comment by russmiles** [comment]
Also validate does not seem to participate in any `controls`, this may well be right but I was wondering. Wdyt @Lawouach ? There's no call to `load_global_controls`, but maybe this is on purpose because validation might not actually cause any events interesting to controls?

**Comment by Lawouach** [comment]
Indeed, I couldn't think of a useful event. But maybe there should be? Open to ideas.

**Comment by russmiles** [comment]
Maybe nothing more than "experiment_validated" when it's complete, or `experiment_validation_started`, `experiment_validation_failed`, `experiment_validation_successful` and `experiment_validation_completed`?

**Comment by Lawouach** [comment]
Sure. We could also assume you want to knwo if validation failed as well.

Please, open an issue on chaostoolkit-lib for this :)

**Comment by russmiles** [comment]
Created issue: https://github.com/chaostoolkit/chaostoolkit-lib/issues/136
