### ISSUE TITLE
Question: How to simulate a login state?

### ISSUE THREAD

**Issue by premkumar-gg** [chaostoolkit/chaostoolkit#132]
May be I'm asking this too early without trying hard. Apologies in that case.

But, could one point in me in the right direction to define a steady state on an authenticated page on a website please.

**Comment by Lawouach** [comment]
Hi!

No stupid question ever.

The steady-state is not really meant to "do" things, but rather to "verify" a global state. There is no way, out of the box, to perform such a login indeed. Or more correctly, it doesn't fit into the steady-state model. Dependening how you run things, I can suggest two approaches:

* Perform the login out of band from a script that calls the chaostoolkit
* Learn the advanced feature that are controls. https://docs.chaostoolkit.org/reference/extending/create-control-extension/ You will be able to achieve what you want that way. But it's indeed more advanced.

**Comment by premkumar-gg** [comment]
What we ended up doing is write a Cypress test (Headless browser testing), and used a process probe to initiate the test.

Also we are looking at another option to call chaostoolkit from our tests.

We may also create a custom control to help do cypress tests easily from within a chaos test.

Thanks for the suggestions. Massive help.

**Comment by Lawouach** [comment]
No pb. I'm looking forward to hear/see what you folks have done! :)
