### ISSUE TITLE
Not met probes in method don't get the experiment to fail

### ISSUE THREAD

**Issue by jjimenezroda** [chaostoolkit/chaostoolkit#135]
As part as the execution of a method, I would like to perform some probes (this scenario is even documented in the official chaos toolkit documentation here: https://docs.chaostoolkit.org/reference/api/experiment/). Eventhough the probe did not met the expected tolerance, the experiment completed successfully.

Here an example:

    method: 
    - type: action
      name: restart_instrument_access_container
      provider: 
        type: python
        module: chaos_sting.actions
        func: restart_container
        arguments:
            containerName: instrumentaccess
      pauses:
        after: 2

    type: probe
      name: instrument_is_in_state_error
      tolerance: true
      provider:
        type: python
        module: chaos_sting.probes
        func: is_instrument_in_state
        arguments:
            allowed_states:
            - 10

And here the results in the journal.json after execution:

    "run": [
        {
          "activity": {
            "type": "action",
            "name": "restart_instrument_access_container",
            "provider": {
              "type": "python",
              "module": "chaos_sting.actions",
              "func": "restart_container",
              "arguments": {
                "containerName": "instrumentaccess"
              }
            },
            "pauses": {
              "after": 2
            }
          },
          "output": true,
          "status": "succeeded",
          "start": "2019-10-31T09:56:43.610351",
          "end": "2019-10-31T09:56:46.044319",
          "duration": 2.433968
        },
        {
          "activity": {
            "type": "probe",
            "name": "instrument_is_in_state_error",
            "tolerance": true,                         <--- Tolerance set to True
            "provider": {
              "type": "python",
              "module": "chaos_sting.probes",
              "func": "is_instrument_in_state",
              "arguments": {
                "allowed_states": [
                  10
                ]
              }
            }
          },
          "output": false,                               <--- Here the output of the probe.
          "status": "succeeded",                    <--- Still it says succeeded when the tolerance is not met.
          "start": "2019-10-31T09:56:48.065868",
          "end": "2019-10-31T09:56:48.108871",
          "duration": 0.043003
        }
      ],

> I would have expected the experiment to fail since one of the probes is not met.

Am I understanding something wrong here?

**Comment by dmartin35** [comment]
I think you're missing the `steady-state-hypothesis` block, in which you shall define your probe, if you want to check for its output tolerance.

A probe, as its own, is only a way to collect information from your system during the experiment. But it does not check for output values when used as an action.
To do so, your probe shall be one of the steady stade hypothesis's probes list. The probe tolerance property is only used when declared as a steady state probe (https://docs.chaostoolkit.org/reference/api/experiment/#steady-state-probe-tolerance)

The steady state hypothesis will allow you to check for some expected outcomes, before & after the actions are executed. This is how you detect deviations (if tolerance is not met) in the system induced by our actions.

```
steady-state-hypothesis:
  title: Asserts using probes on the system
  probes:
  - type: probe
    ...
```

I hope this helps

**Comment by dmartin35** [comment]
however if you're interested about interrupting your whole experiment, from an activity, you can have a look into controls
https://docs.chaostoolkit.org/reference/extending/create-control-extension/#interruptinng-the-execution

**Comment by jjimenezroda** [comment]
Thanks for the clarification. I can close the issue then.
