### ISSUE TITLE
Currently an experiment's method needs at least one activity, should this restriction be relaxed?

### ISSUE THREAD

**Issue by russmiles** [chaostoolkit/chaostoolkit#136]
Right now it is not possible to have an empty, or even missing, `method` block. Sometimes I've found this useful though, to simply use a steady-state hypothesis as a type of examination of a target system's normalcy.

I wonder if we could relax this restriction so that an empty method could be specified, or even no method at all being present?

**Comment by Lawouach** [comment]
Interesting. That goes the oppositie direction of what has been promoted so far. You don't know your steady-state and you introduce perturbation.

**Comment by russmiles** [comment]
Not sure I understand. I mean introduce no perturbation but use the steady state as a check on its own?

**Comment by russmiles** [comment]
Yes, I see what you mean. It is enabling the alternate case, which I can now see, where only steady-state is know and useful for the time being.

**Comment by Lawouach** [comment]
I'm happy with the change. I can see the value. I think it'd be nice to build a documentation for both so that people know why they'd pick one over the other.

**Comment by russmiles** [comment]
Go as far as making “method” optional, or only allowing 0 activities... I kinda prefer the former?

**Comment by Lawouach** [comment]
yeah, it'd be clearer
