### ISSUE TITLE
Add yaml and json info to `chaos --help` and `chaos run --help`

### ISSUE THREAD

**Issue by russmiles** [chaostoolkit/chaostoolkit#137]
At the moment the help does not indicate that some commands can accept json and yaml. It would be nice if those commands did.

**Comment by nstjelja** [comment]
Dears, do we want to add YAML information to some other commands or is the PR we merged in enough to close this issue?

**Comment by nstjelja** [comment]
@russmiles  do you think we can close this issue or do you think we can do something else?

**Comment by russmiles** [comment]
I think we can close this one and raise separate issues for other yaml-related clarifications.
