### ISSUE TITLE
Report all experiment validation errors at once

### ISSUE THREAD

**Issue by dmartin35** [chaostoolkit/chaostoolkit#144]
Currently, when a `chaos validate` command is run, it shows the first error and exits. This is a process to repeat when fixing each error, when using an experiment that contains multiple syntax issues.

It could be nice to do a full validation of the file and outputs all errors at once. It can either be default behavior or behavior to be activated with a CLI flag (`--full-validation`, `--global`, ...) 

The following experiment contains multiple errors:
```
{
    "version": "1.0.0",
    "title": "Invalid syntax experiment",
    "description": "This experiment contains multiple synatx errors to be raised at validation step",
    "tags": [
        "invalid"
    ],    
    "steady-state-hypothesis": {
        
    },
    "method": [
        {"type": "invalid"}
    ],
    "rollbacks": [{"type":"invalid"}]
}
```

**Comment by nstjelja** [comment]
this makes sense, specially in a CI setting.

**Comment by nstjelja** [comment]
I went throught the chaos-lib and we are using exceptions to indicate failures. I was thinking we could change the methods for validation in chaos-lib to instead of breaking immediatelly to collect all issues and then report them in one go.

**Comment by dmartin35** [comment]
This is a good idea but such a change has impact on the internal lib, as it changes the initial design on multiple nested validation function.
might want to ear from @Lawouach what he thinks of that. 

Also would it have impact on the extensions ? 

It's not blocking for now, I could submit a PR when l'll get more time

**Comment by Lawouach** [comment]
Hi all,

Good feature request. I don't think we need a new flag, this should become the default behavior and not impact compatibility.

However, there is a lot of workto change the code internally I'm afraid. This will take some work.

**Comment by dmartin35** [comment]
If that's ok with you guys, l'll start a PR on that issue

**Comment by nstjelja** [comment]
@dmartin35  If you want I would like to help you with the PR. I have looked at the code but im not that familiar with the internals to dare to refactor it. 

Question what would be your idea for development. 

I saw that we are basically raising an exception and then printing that exeption as a result. What would be the change? Change the base exception to collect multiple error messages or multiple excpetions (like python activity validation sub validation) and then print it from there?

**Comment by dmartin35** [comment]
@nstjelja sorry for late response

I thought about 2 ways of implementing that full syntax validation:

* Handle a list of all exceptions:  for each sub-function, gather a list of exception instances and returns it to parent call. This list is appended/extended through the sub-functions calls. In the main experiment function, we could check whether the errors list is not empty, then iterate over each one to log it as error, then finally raise an invalid experiment error (to be logged by the CLI).
*this loses the module & line of each error where it was created when logging from another place*
* Log errors where we detect them and return a boolean that indicates whether the (sub-)function has *raised* an error. The boolean return value from sub-functions shall be aggregated with logical operator. Last in main , we shall check the value of that *global* boolean then raise accordingly
(for CLI exception catch)

does it make sense to you ? or do you have any other ideas of implementation ?

**Comment by dmartin35** [comment]
I've pushed my work in progress https://github.com/dmartin35/chaostoolkit-lib/tree/validate-all-errors in case you guys want to have a look.

**Comment by nstjelja** [comment]
@dmartin35  i think i would suggest going through option 1. The only risk/issue/ problem i see is that the original function was written with the flow being interrupted by the exception being raised so it would require us to write code in amore defensive manner.

**Comment by nstjelja** [comment]
@dmartin35 went through the code, looks ok. I put just one comment , take a look and see if it makes sense for u.

**Comment by dmartin35** [comment]
This improvement is still in progress...

But it does currently break a lot of unit tests, that are expecting to fail, we might need @Lawouach opinion on how to capture the expected validation error in unit tests

**Comment by Lawouach** [comment]
After a discussion offline with @dmartin35, I realised there are two things here:

1. a short term solution to allow for all validation errors to be displayed at once
2. a long term requirements for a better validation mechanism. I'd suggest we start considering creating proper schemas of expected data (using [pydantic](https://pydantic-docs.helpmanual.io/) for instance?) so that the validation would be done via this mechanism

I will look at the code and see what can be achieved for 1.
