### ISSUE TITLE
Assembly of all *Shell scripts that used in chaostoolkit

### ISSUE THREAD

**Issue by xpdable** [chaostoolkit/chaostoolkit#146]
### Background
Some users as for now attempts several chaos experiments in the operation system level, i.g. burn cpu, network latency, or even kill a specific process... etc. The main mechanism of implement those kinds experiments are rely on an agent inside each machine. For instance, AWS has [System Manager](https://docs.aws.amazon.com/systems-manager/latest/userguide/ssm-agent.html) and Azure has [VM Run Command function](https://docs.microsoft.com/en-us/rest/api/compute/virtual%20machines%20run%20commands/runcommand). Also for some other extensions like SaltStack, it also runs in this way.
The agent allows users run remote scripts on the machine, for example shell in Linux/Unix and PowerShell in Windows. Most functions, for instance like burn cpu is implemented by this script in Azure for [Linux/Unix](https://github.com/chaostoolkit-incubator/chaostoolkit-azure/blob/master/chaosazure/scripts/cpu_stress_test.sh) and [Windows](https://github.com/chaostoolkit-incubator/chaostoolkit-azure/blob/master/chaosazure/scripts/cpu_stress_test.ps1) 
The scripts will be run remotely on your target machine to achieve the experiment purpose.

### Challenge
Scripts will be always risky, especially you're running them on a remote machine. For example if you execute something bad that burn the cpu continuously without stop and exit, you may lost the machine somehow that exceeds the chaos experiments blast radius.
- So to ensure the safety of our scripts would be very critical. 
- And to manage all the script in a unified place/repo or artifact manage tools would be also necessary.

### Possible Solutions
1. Chaostoolkit may suggest and maintains some best practice of explicit scripts corresponds to specific experiments. 
2. On the other hand, Chaotoolkit may also allow users to customize own scripts, for example AWS System Manager could fetch script from Github or S3 buckets.
3. Chaostoolkit should keep the script up-to-date, away from bugs/vulnerabilities of OS. Open to the community for review.
4. The scripts for one experiment that across platforms, i.e. Unix / Linux / Windows should be in the same scope in the functional level. Meaning, for example PowerShell and Shell should do the same thing.

This topic is open to discuss, @Lawouach @buderre

**Comment by xpdable** [comment]
An experiment on AWS is addressed by my colleague:
Might be some useful hint to the violation of the scripts

We try to kill AWS SSM Agent.
1)  Use SSM Run Command `yum remove -y amazon-ssm-agent` is restricted
2) However we succeed in running a script as below :) 
    Meaning SSM agent could be uninstalled in this way which is a potential risk
```Shell
#!/bin/bash

wget https://p1000p-tool-script.s3.cn-north-1.amazonaws.com.cn/scripts/tw-sh/amazon-ssm-agent-v-2-3-662-0.rpm -O /tmp/amazon-ssm-agent.rpm
yum remove -y amazon-ssm-agent
yum localinstall -y /tmp/amazon-ssm-agent.rpm
systemctl restart amazon-ssm-agent
```

**Comment by Lawouach** [comment]
I think it's a clear description of the current challenge indeed.

I feel shell scripts must be easy to audit and control because some security teams might not tolerate them otherwise. So, keeping them in their own repo (if they can be applied cross cloud providers that is) would help focusing the security effort to high standards.

Good documentation and best practices would be a great collateral.
