### ISSUE TITLE
Use f-strings in code

### ISSUE THREAD

**Issue by dmartin35** [chaostoolkit/chaostoolkit#154]
We could leverage the use of python f-strings for easier/better string formatting in the code.

f-strings have been introduced in python 3.6
the following package backports the f-strings to python<3.6: https://github.com/asottile/future-fstrings

As our code is python 3.5 compliant, this is something we could have a look at, if we want to use f-strings at some point

**Comment by amitkrishna** [comment]
Hi @dmartin35 would like to know it this issue is fixed earlier . I would like to have some more inputs as to how to integrate this , should this be in logger functions.
