### ISSUE TITLE
Confusing message when a `process` based activity refers to a file/script that is not executable

### ISSUE THREAD

**Issue by russmiles** [chaostoolkit/chaostoolkit#160]
If you accidentally refer to a file that is not executable, the toolkit responds with the following message when doing a `validate` or `run` command:

```
[2020-01-30 16:00:27 ERROR] path 'None' cannot be found, in activity 'my-activity'
```

If possible it would be nice if the toolkit pointed out that you were referring to a file that was not executable so this could be debugged more easily.

**Comment by dmartin35** [comment]
I opened an issue on the lib, as this is in the core; see https://github.com/chaostoolkit/chaostoolkit-lib/issues/159
