### ISSUE TITLE
Feature Request - Reporting after the Chaos Test

### ISSUE THREAD

**Issue by codemystyle** [chaostoolkit/chaostoolkit#161]
it would be good to have some reporting document after the test is completed, something like generating HTML report with some good GUI of what happened during the test.

**Comment by grexe** [comment]
there's the reporting plugin that offers HTML and PDF reports:
https://github.com/chaostoolkit/chaostoolkit-reporting

See also chaostoolkit main docs:
https://docs.chaostoolkit.org/reference/tutorial/#report-on-your-findings
