### ISSUE TITLE
Share roadmap

### ISSUE THREAD

**Issue by ojongerius** [chaostoolkit/chaostoolkit#165]
Would you be open to sharing the roadmap for this project? There is lots of interesting information in #74.  Maybe use that to flesh it out and share it in the README.MD or a ROADMAP.MD?

Publishing this will help folks like myself validate if the features they are looking for are compatible with the projects ambition, and possibly even start work on some of those features.

**Comment by Lawouach** [comment]
Hello @ojongerius I am so sorry I never replied to this suggestion.

Yes, that would be definitely a great idea to do so. So bear with me a little more while I set one up :)

**Comment by Lawouach** [comment]
Just drafted a document. I now need to add milestones and issues to the https://github.com/chaostoolkit/projects/5

**Comment by Lawouach** [comment]
I have now associated issues to the main roadmap board https://github.com/orgs/chaostoolkit/projects/5

I'm going to close this issue and hope we stick to making that board alive and well. 

The next milestones for each project should usually be its next minor version.
