### ISSUE TITLE
Provide log in json format as --log-format json in console

### ISSUE THREAD

**Issue by xpdable** [chaostoolkit/chaostoolkit#173]
It is very excited to see that we have had the console output in json.
As for my usage of chaos, I need to gather the log as well in order to do some value-add calculation and normalization before I finially push all of these into ElasticSearch.
Although we I the json output in json, the --log-file is still written in the original format.
Would it be possible to set some flag to enable the log that also write in json?
The pain point is the console output is not so easy to deal as a log file. 
Thanks.

**Comment by xpdable** [comment]
Update, the console is actually wrap each output line into one JsonObject. To consider all console output as a whole, it is neither a JsonObject nor a JsonArray (lack of comma at each end of } ). So it would be re-considered how to provied. ty.

**Comment by Lawouach** [comment]
I think it's a fair point. I need to see how I could achieve that.

**Comment by Lawouach** [comment]
See also #120
