### ISSUE TITLE
Allow to pass configuration via the CLI as arguments

### ISSUE THREAD

**Issue by Lawouach** [chaostoolkit/chaostoolkit#175]
This could look like this:

```
$ chaos run --var "service_url=http://example.com" --var "count=1" experiment.json
```

but also, when the data is passed as-is as a json payload:
```
$ chaos run --var-file myvar.json experiment.json
```

or finally as a [dotenv](https://pypi.org/project/python-dotenv/) file:

```
$ chaos run --var-file myvar.env experiment.json
```

**Comment by Lawouach** [comment]
In all instances, the specified values should take precedence over the ones in the experiment.

Also, if an var file and vars are passed at the same time, the vars take precedence over any others, including the var file.

**Comment by praveentata** [comment]
Hello,

We are not able to get this working.
This is the error that we are getting:


```
ubuntu@ip-x-x-x-x:~$ kubectl logs -f  pod/atlantia-chaos-testing-hn8c5 -n csp
[2022-12-08 16:05:22 DEBUG] [cli:70] ###############################################################################
[2022-12-08 16:05:22 DEBUG] [cli:71] Running command 'run'
[2022-12-08 16:05:22 DEBUG] [cli:75] Using settings file '/root/.chaostoolkit/settings.yaml'
Usage: chaos run [OPTIONS] SOURCE
Try 'chaos run --help' for help.

Error: no such option: --var-file /tmp/token.env
```

I can ensure that the file path is correct.
We encountered the same error with `--var` flag as well

**Comment by praveentata** [comment]
It worked when passing the values as suggested:

```
args:
        - --verbose
        - run
        - --var-file
        - /tmp/token.env
        - /experiment/terminate-all-pods.yaml
```

Thanks for the help
