### ISSUE TITLE
Do not show secret detail in journal.json

### ISSUE THREAD

**Issue by xpdable** [chaostoolkit/chaostoolkit#178]
Configuration that contains secret details may show up in journal.json.
Secrets may need to be wrapped by *****

**Comment by Mickael-Roger** [comment]
Do you think it should need a specific command line option or be the default behavior?

**Comment by Lawouach** [comment]
Configuration are not meant to hide secret values. So it's expected that they are all get displayed. I'm not sure we could detect a config value is meant to be a secret?

**Comment by Mickael-Roger** [comment]
The idea was at least to hide secrets values from be displayed in journal.json. 
It is true that best practice should be to use env var or vault for secrets, but in case you don't or can't, don't you think it's better to not display them in journal that can be sent to different teams or tools?

The question is do you think it can break something is the usage of journal.json made by user? (except the unit tests that make an assert for secrets value in journal ;-) )

**Comment by Lawouach** [comment]
I still don't understand how ctk can differentiate a value to hide from a value that is not sensitive when it comes to configuration.

**Comment by Mickael-Roger** [comment]
It cannot (at least easily)

But just hidding values that is contained in secrets block is probably not perfect but at least a first step in the security scope

**Comment by Lawouach** [comment]
Yes, hiding those in the secrets block makes total sense. I will not hide values from the configuration block however.
