### ISSUE TITLE
Add one global provider type

### ISSUE THREAD

**Issue by michael-gehtman-wix** [chaostoolkit/chaostoolkit#184]
`experiment-type`: a global JSON experiment key to assign to all providers type key.
Add a feature that can handle the "experiment-type" key in an experiment JSON file.

usage: 
 
```JSON {
    "version": "1.0.0",
    "title": "a dummy test",
    "description": "N/A",
    "tags": [],
    "experiment-type": "python", <- this is the additional key
    "steady-state-hypothesis": {
        "title": "a steady state hypo",
        "probes": [
            {
                "type": "probe",
                "name": "all_microservices_healthy",
                "provider": {  <- no need for type key
                    "module": "chaosk8s.probes",
                    "func": "all_microservices_healthy",
                    "arguments": {
                        "ns": "default"
                    }
                },
                "tolerance": "true"
            }
        ]
    },
    "method": [
        {
            "type": "action",
            "name": "kill_microservice",
            "provider": { <- no need for type key
                "module": "chaosk8s.actions",
                "func": "kill_microservice",
                "arguments": {
                    "name": "true",
                    "ns": "default",
                    "label_selector": "N"
                }
            }
        }
    ]
}
```

Handling:
After loading the experiment JSON file, a recursive function will run all over the keys of the experiment object (to ensure all providers will be assigned no matter what object holds it).
Finding all the "provider" dictionaries and add them to the type value from the "experiment-type".
If a type already exists in the provider no assignment will occur (that you will be able to add a different type then the global).
If some exception will happen (can't see any now, but just in case), the function will return the original untouched experiment preserving the original missing type validation error.
If an unsupported provider type will be passed, the validation will return the usual error message.

## Note
This implementation probably should not be in `chaostoolkit.cli`, just a demo to show the concept.
guess somewhere in `chaostoolkit-lib` before the validation is happening.

This is the link to my fork with the changes I did.
https://github.com/michael-gehtman-wix/chaostoolkit/pull/1

**Comment by alexander-gorelik** [comment]
@Lawouach All our provider currently is python so we thought of this enhancement to reduce the json size.

**Comment by Lawouach** [comment]
Hey folks, not a bad idea.

This would also require a change on the spec as I believe the `type` is mandatory.

That said, your function could actually be a controller that is globally enabled so you wouldn't even need to change the spec. Just make sure people use the bundle of controls you guys come up with.

**Comment by alexander-gorelik** [comment]
Can you please elaborate on the last two lines, I am not sure that I understand

**Comment by Lawouach** [comment]
Controls have two properties that can be of use here:

* they can modify the experiment on the fly
* they have a handler before validation gets called (the `after_loading_experiment_control` handler). 

If you create a control module with that handler and register it from your settings file (so it's always applied on any experiment on that machine), then you should be good.

https://docs.chaostoolkit.org/reference/extending/create-control-extension/#declare-it-in-your-settings

**Comment by alexander-gorelik** [comment]
That's reasonable
