### ISSUE TITLE
Drop python 3.5 support - EOL -

### ISSUE THREAD

**Issue by dmartin35** [chaostoolkit/chaostoolkit#194]
Python 3.5 will reach its "end of life" at the end of September 2020.

We shall consider upgrading minimal version to python 3.6.

cc https://github.com/chaostoolkit/chaostoolkit-lib/issues/187

**Comment by glsutter** [comment]
Didn't see a question about Python version in the repo. Does Chaos Toolkit require Python 3.5, or does it also work with later versions?

**Comment by dmartin35** [comment]
CTK currently works with Python 3.5+ ie nothing is blocking from using it with a more recent python version, 
unless you need an extensions that specifically requires py 3.5

**Comment by Lawouach** [comment]
Pinning chaoslib to strictly less than 1.19.0 as it'll be the last one supporting Python 3.5

**Comment by Lawouach** [comment]
Last release with Python 3.5 support is now 1.8.1
