### ISSUE TITLE
Configuration files require the main experiment file to have the keys from the configurations.

### ISSUE THREAD

**Issue by WixoLeo** [chaostoolkit/chaostoolkit#203]
Fantastic day!

There is a little issue with the configurations.

For example I have this experiment.json

```json
{
  "version": "1.0.0",
  "title": "test",
  "description": "test",
  "configuration": {
    "myarg": "exp.json",
    "another_arg": "" // Must be included to work
  },
  "tags": [
    "network",
    "lala"
  ],
  "steady-state-hypothesis": {
    "title": "Check something",
    "probes": [
      {
        "name": "My probe",
        "description": "My best probe",
        "tolerance": {
          "type": "regex",
          "pattern": "exp.json",
          "target": "stdout"
        },
        "type": "probe",
        "provider": {
          "type": "process",
          "path": "echo",
          "arguments": "${myarg}"
        }
      },
      {
        "name": "My probe",
        "description": "My best probe",
        "tolerance": {
          "type": "regex",
          "pattern": "another.json",
          "target": "stdout"
        },
        "type": "probe",
        "provider": {
          "type": "process",
          "path": "echo",
          "arguments": "${another_arg}"
        }
      }
    ]
  },
  "method": [],
  "rollbacks": []
}
```

And var-file:
```json
{
  "configuration": {
    "another_arg": "another.json"
  }
}
```

Launching via `chaos run exp.json --var-file config.json`
So the experiment works right now, but when you have a big configuration, it's quite annoying have to place empty values to the config keys. Why not to just exclude them? So that if I provide `"another_arg"` from `config.json`, I don't have to place an empty one in the `experiment.json`.

**Our suggestion:** If none of the configurations contain such attribute, only then raise an error.

**Comment by Lawouach** [comment]
Hey there,

I can the issue with large configuration indeed. I think the rationale was to ensure the experiment documents clearly its expectations. I need to check but it would be good if the ctk validation could say "hey you're using a var that was not never found neither in the inlined configuration section nor from a config var". So at least we get notified about this.

**Comment by WixoLeo** [comment]
> Hey there,
> 
> I can the issue with large configuration indeed. I think the rationale was to ensure the experiment documents clearly its expectations. I need to check but it would be good if the ctk validation could say "hey you're using a var that was not never found neither in the inlined configuration section nor from a config var". So at least we get notified about this.

Of course, that would be great!
