### ISSUE TITLE
Can I implement "retry until met" for probe?

### ISSUE THREAD

**Issue by laixintao** [chaostoolkit/chaostoolkit#204]
Hi I have checked this issue: https://github.com/chaostoolkit/chaostoolkit/issues/104

But I also want to know if some condition happed during continuously evaluate the steady-state hypothesis

Can I implement a probe that works like this:

1. Continuously try probe1, once it met the steady-state hypothesis;
2. Then start to evaluate probe2, once it passes, then;
3. Start probe3 ...

**Comment by Lawouach** [comment]
Hello @laixintao 

apologies for being slow. Retry doesn't exist in CTK. There is nothing designed for it. Howevere this might be interesting to add. Depends if the experiment definition needs to know about the repetition (should it be declared in the json?).

**Comment by WixoLeo** [comment]
We also need this feature haha

Currently we've created our own custom probe that accepts the "activity" json structure and it's basically polling for something to happen. It works like this:

```json
{
      "type": "action",
      "name": "Polling for healthy newly created instance",
      "provider": {
        "type": "python",
        "module": "anonymous.probes.poll",
        "func": "polling_probe",
        "arguments": {
          "module": "ourplugin.probes",
          "func": "server_is_up",
          "tolerance": true,
          "interval": 60,
          "timeout": 3300,
          "arguments": {
            "server_name": "hello_world"
          }
        }
      }
    },
```

There are 3 ways to stop the poller:
* Return the expected tolerance (the experiment will continue)
* Reach the timeout (the experiment will exit gracefully with rollbacks)
* Throw an exception (the experiment should exit gracefully with rollbacks) (this is needed in case there is a connection problem, like an error 500 or something, or bad syntax, could be anything)

**Comment by laixintao** [comment]
@WixoLeo Yes, I am thinking something like that.
But for my case, I just figure out that I can just use continues mode for probe, because the rule is if the last probe said success, then the result is a success, no matter how many times failed before. So that meets my needs already.

But your method is very helpful.
