### ISSUE TITLE
Azure blank documentation

### ISSUE THREAD

**Issue by pioardi** [chaostoolkit/chaostoolkit#209]
**Describe the bug**
Azure doc https://docs.chaostoolkit.org/drivers/azure/ display a blank page

**Runtime versions**
N/A

**To Reproduce**
Open the page https://docs.chaostoolkit.org/drivers/azure/

**Expected behavior**
See something like 
https://docs.chaostoolkit.org/drivers/aws/

**Additional context**
I am new to this project so I am not sure if this is an issue or a missing feature for Azure.
I would like to look into Chaos Engineering for azure infrastructure and would be great to use ChaoosToolKit since that seems to be really well implemented and extensible.

**Comment by pioardi** [comment]
ping

**Comment by CharlieMoon37** [comment]
Could you give this another try and let me know the result - it seems to work perfectly for me?
