### ISSUE TITLE
Fix 'tolerance' for process probes

### ISSUE THREAD

**Issue by twuyts** [chaostoolkit/chaostoolkit#21]
I can not figure out how to create a steady state hypothesis with a process probe. The problem comes from the way the tolerance is compared to the output of the process.

Ideally, when you define a probe of type 'process' for the steady state hypothesis, and the tolerance is of type 'int', it should simply check the return code of the process against the tolerance.

Optionally, it might be useful to handle tolerance of type str, by comparing it to stdout

I temporarily fixed the 'int' problem by applying this change:
```
diff --git a/chaoslib/provider/process.py b/chaoslib/provider/process.py
index a6d2b4e..50a9b44 100644
--- a/chaoslib/provider/process.py
+++ b/chaoslib/provider/process.py
@@ -49,11 +49,11 @@ def run_process_activity(activity: Activity, configuration: Configuration,
     except subprocess.TimeoutExpired:
         raise FailedActivity("process activity took too long to complete")
 
-    return (
-        proc.returncode,
-        proc.stdout.decode('utf-8'),
-        proc.stderr.decode('utf-8')
-    )
+    return {
+        "status": proc.returncode,
+        "stdout": proc.stdout.decode('utf-8'),
+        "stderr": proc.stderr.decode('utf-8')
+    }
```

**Comment by Lawouach** [comment]
Yeah, the whole `tolerance` area does need some work. I wanted to carry simplicity with common checks (like int, bool...) but I realise this may be confusing. I think your intuition regarding the process probe checking the status code may be a good one. Magic has its drawbacks sometimes.

**Comment by Lawouach** [comment]
Thanks a lot for the PR.

Could you offer a sample experiment showing how the hypothesis looks with that payload please? Just for reference.

**Comment by Lawouach** [comment]
A proposal, that we discussed with @twuyts:

Support the commmon generic native types (as we already do):
```
"tolerance": int | str | tuple(float, float)
```
But also calling another activity to perform the validation (again, already done):

```
"tolerance": {
   "type": "probe"....
}
```

Finally, here is the new proposal:

Validating through a regex:
```
"tolerance": {
   "type": "regex",
   "value": "...."
}
```

Validating the process output:
```
"tolerance": {
   "type": "process",
   "stdout": "REGEX"
}
```

Or:

```
"tolerance": {
   "type": "process",
   "code": 0
}
```

Or:

```
"tolerance": {
   "type": "process",
   "stderr": "REGEX"
}
```

This should make it easier to extend and provider gradually more powerful validators.

**Comment by twuyts** [comment]
Should the process probe return
```
{ 
  status: ..., 
  stdout: ..., 
  stderr: ...
}
```
or
```
{ 
  returncode: ..., 
  stdout: ..., 
  stderr: ...
}
```

If we go with 'status'  then it follows the same tolerance checks as HTTP calls, so you can simply say 
`"tolerance": 0`
to check for a successful outcome of the process probe (i.e. assuming the process returned 0)

If we go with 'returncode' then we can still do this if we also adapt all the tolerance checks to look at the returncode field as well as the status field, like this: 

```
@within_tolerance.register(int)
def _(tolerance: int, value: Any, secrets: Secrets = None) -> bool:
    if isinstance(value, dict):
        if "status" in value:
            return value["status"] == tolerance
        if "returncode" in value:
            return value["returncode"] == tolerance

    return value == tolerance
```

It's not a very clean solution IMHO, but it works.

Or... we could not change the checks, and explain in the docs how to check for returncode with a tolerance dict, as proposed above: 
```
"tolerance": {
   "type": "process",
   "code": 0
}
```
But this requires something that is not implemented yet.

So a long comment to come back to a simple question: which name would be preferred, status or returncode?

**Comment by Lawouach** [comment]
Yeah, good comment @twuyts. We need to unify as much as we can to keep the code simple while remaining comprehensible for the user.

**Comment by Lawouach** [comment]
I have merged your PR and I'm going to continue improving the tolerance mechanism from here :)

**Comment by Lawouach** [comment]
I have now merged a large addition that should hopefully improve the tolerance validation mechanism with either regex or JSON path.

I'm going to update the docs accordingly and will close this issue.

**Comment by Lawouach** [comment]
This is available now at http://chaostoolkit.org/reference/api/experiment/#steady-state-probe-tolerance and http://chaostoolkit.org/reference/api/experiment/#process-provider
