### ISSUE TITLE
Bug with restarting a script

### ISSUE THREAD

**Issue by Hiltzaile6** [chaostoolkit/chaostoolkit#219]
Anyone have any idea why I am getting this error? This is the part of my experiment where it errors. That is indeed the correct path, I am trying to get CTK to execute the shell script named "activemq".

![image](https://user-images.githubusercontent.com/86000926/122219292-4c397580-ce7d-11eb-940e-2d79584e882f.png)

![issue](https://user-images.githubusercontent.com/86000926/122219251-3fb51d00-ce7d-11eb-9919-a115e403988e.PNG)

**Comment by Lawouach** [comment]
Hello,

Can you do `ls ~/ActivateMQ/apache-activemq-5.16.2/bin/activatemq` please?

**Comment by Hiltzaile6** [comment]
> Hello,
> 
> Can you do `ls ~/ActivateMQ/apache-activemq-5.16.2/bin/activatemq` please?

![image](https://user-images.githubusercontent.com/86000926/122220757-a424ac00-ce7e-11eb-8524-3443a8cffe40.png)
