### ISSUE TITLE
Question : Do chaostoolkit have  probe/action to test RabbitMQ messaging

### ISSUE THREAD

**Issue by prasadchavan231989** [chaostoolkit/chaostoolkit#222]
We have multiple microservices which serves request solely on what is received from RabbitMQ queues (no REST endpoints) . We plan to use chaostoolkit , but I am wondering whether it has  probes or action for sending/receiving  a message from queues which could be used in experiment files?

**Comment by Lawouach** [comment]
Hello,

It doesn't have any AMQP extension indeed. It'd be a nice addition for sure.
