### ISSUE TITLE
Error in documentation for Setting the region

### ISSUE THREAD

**Issue by lefamoffat** [chaostoolkit/chaostoolkit#253]
**Describe the bug**
In the [Setting the region](https://chaostoolkit.org/drivers/aws/#setting-the-region) part of the documentation the `env` and `type` value should be switched.

**Runtime versions**
Please run:

```
$ python --version
$ chaos info core
$ chaos info extensions
```

**To Reproduce**
Configure your project as described in the docs with
```
{
    "configuration": {
        "aws_region": {
            "env": "type",
            "key": "AWS_REGION"
        }
    }
}
```

<img width="1153" alt="Screenshot 2021-11-16 at 14 08 15" src="https://user-images.githubusercontent.com/49285031/141991418-d59717c3-9c57-43ad-b445-d154d9f68036.png">

**Expected behavior**
No errors and for the CLI to take the correct value from `env`

<img width="1152" alt="Screenshot 2021-11-16 at 14 08 28" src="https://user-images.githubusercontent.com/49285031/141991471-1f660088-02ef-47a9-aa4b-51549f2a8988.png">

**Additional context**
The fix is just to switch the two, i.e. 
```
{
    "configuration": {
        "aws_region": {
            "type": "env",
            "key": "AWS_REGION"
        }
    }
}
```
like it is done [here](https://chaostoolkit.org/reference/api/experiment/#environment-secrets)

**Comment by Lawouach** [comment]
Fixed by https://github.com/chaostoolkit-incubator/chaostoolkit-aws/pull/128
