### ISSUE TITLE
Integers are being quoted in resulting JSON structure when passed in via the environment, resulting in Type Cast Errors in downstream systems

### ISSUE THREAD

**Issue by dav1dc-pcf** [chaostoolkit/chaostoolkit#254]
**Describe the bug**

```
[2021-11-24 18:37:32 ERROR]   => failed: chaoslib.exceptions.ActivityFailed: Turbulence atttack failed: {
      "error": "Unmarshalling task type 'Stress': json: cannot unmarshal string into Go struct field StressOptions.NumCPUWorkers of type int"
    }
```

Is occurring in the downstream Turbulence/Stress system call behind the ChaosTK driver, this appears to be a result of the quoting scheme that chaostk/python are using for inputs passed in via the environment.

consider the following configuration definition fragment:

```
configuration: {
    "cpu_workers": {
      "type": "env",
      "key": "STRESS_CPU_NUM_WORKERS",
      "default": 2
    }
...
}
```

When no environment variable for STRESS_CPU_NUM_WORKERS is set in the environment, then the "default" value of 2 is not quoted in the resulting JSON body (correct integer handling), and we can see this in the log when the attack works properly:

```
[2021-11-24 18:14:40 DEBUG] [actions:30] Posting `{'Tasks': [{'Type': 'Stress', 'NumCPUWorkers': 2 ...
```

but as soon as I **export STRESS_CPU_NUM_WORKERS=3** and re-run the experiment, I see this in the log (and the attacks fails with the very first error message described in this bug report at the top):

```
[2021-11-24 18:15:58 DEBUG] [actions:30] Posting `{'Tasks': [{'Type': 'Stress', 'NumCPUWorkers': '3' ...
```

which quotes the integer with single quotes, and that breaks the integer parsing by GO in the downstream Stress/Turbulence binary.

I have also tried this with no success either:

```
chaos run --no-verify-tls --var cpu_workers=3 experiments/turbulence/stress_cpu_random_job.json
```

How do I pass an Integer in via environment variable and have it quoted correctly in the JSON passed to Turbulence?
(which would be no quoting at all for integers)

**Runtime versions**
Please run:

```
# python3 --version
Python 3.6.9

# chaos info core
NAME                VERSION
CLI                 1.10.1
Core library        1.23.0

# chaos info extensions
NAME                                    VERSION   LICENSE                       DESCRIPTION
chaostoolkit-cloud-foundry              0.7.1     Apache License Version 2.0    Cloud Foundry
chaostoolkit-turbulence                 0.1.0     UNKNOWN                       Chaos Toolkit Turbulence support
```

**To Reproduce**

Define a configuration variable for a simple integer as shown above, and have it be passed along in the resulting JSON payload without quotes (proper integer handling).

**Expected behavior**

Integers in JSON have no quotes, so I would expect an integer value to not have quotes in the resulting JSON body

**Additional context**

This only seems to be a problem when the downstream system expects strict typing adherence in the JSON body.

**Comment by ciaranevans** [comment]
@dav1dc-pcf this is indeed a limitation of Environment variables, as they are only ever evaluated to strings, whereas the default value is merely loaded from the JSON directly.

Perhaps we could have a type field @Lawouach that allowed for primitive types to be declared for when we load env vars?

**Comment by Lawouach** [comment]
Hello, totally makes sense this is not a desirable behavior.

But in bash terms (or any other shell), environment variables are strings. They have no types but strings. Our option could be to follow what we did with extra variables to indicate the type:

```
export STRESS_CPU_NUM_WORKERS=int:2
```

That would be parsed by ctk.

**Comment by ciaranevans** [comment]
@Lawouach on the expectation that people might use those environment variables elsewhere - would it not be better to instead allow for a new entry in configuration that denotes the type? 

Something like:

```
configuration: {
    "cpu_workers": {
      "type": "env",
      "env_var_type": "int"
      "key": "STRESS_CPU_NUM_WORKERS",
      "default": 2
    }
...
}
```

Where CTK would check for `"env_var_type"` as a key if the configuration entry is `"env"`? Then similarly to the `type:value` way, we'd just default to `str` if not provided

**Comment by Lawouach** [comment]
Much better idea indeed!

Le lun. 29 nov. 2021 à 11:36, Ciaran Evans ***@***.***> a
écrit :

**Comment by ciaranevans** [comment]
Hey @dav1dc-pcf would you mind running:

```
pip install git+https://github.com/chaostoolkit/chaostoolkit-lib.git@master#egg=chaostoolkit-lib
```

And making your configuration block look like:

```
configuration: {
    "cpu_workers": {
      "type": "env",
      "env_var_type": "int"
      "key": "STRESS_CPU_NUM_WORKERS",
      "default": 2
    }
```

And confirming if this now works for you?

I've added support for a `env_var_type` key which will accept `"str"`, `"int"`, `"float"`, or `"bytes"`

**Comment by dav1dc-pcf** [comment]
Wow, that was a quick response AND a new feature ready for us to test in a debug build - I ♥️ you folks!

I can confirm that YES, this does solve our issues. A quick re-cap I added the following to all INT types in the experiment definition:

```
    "cpu_workers": {
      "type": "env",
      "key": "STRESS_CPU_NUM_WORKERS",
      "env_var_type": "int",
      "default": 2
    },
    "hdd_workers": {
      "type": "env",
      "key": "STRESS_HDD_NUM_WORKERS",
      "env_var_type": "int",
      "default": 1
    },
...
```

and I can see in the chaostoolkit.log file that the JSON payload destined for the Turbulence API server is properly formed with respect to integer handling:

```
[2021-12-01 08:15:43 DEBUG] [actions:30] Posting `{'Tasks': [{'Type': 'Stress', 'NumCPUWorkers': 2, 'NumHDDWorkers': 1, 'HDDWorkerBytes': '512K', 'NumIOWorkers': 2, 'NumMemoryWorkers': 1, 'MemoryWorkerBytes': '15K', 'Timeout': '2m'}], 'Selector': {'Deployment': {'Name': 'cf-abcdefg12345678'}, 'Group': {'Name': 'diego_cell'}, 'ID': {'Limit': 1}}}` to `https://TURBULENCE_URL/api/v1/incidents`
[2021-12-01 08:15:43 DEBUG] [actions:35] attack submitted sucessfully: {
...
```

Well done and a quick turn around - many many thanks!

Any idea how soon this might show up in the mainline releases??

**Comment by ciaranevans** [comment]
Haha no worries @dav1dc-pcf, glad we could help, your thorough issue made it easier!

As to releases. I can look at cutting a new one tomorrow as this isn't a breaking change. @Lawouach - does that seem alright to you?

**Comment by Lawouach** [comment]
Awesome!

Well done Ciaran. A release tomorrow is appropriate indeed.





Le mer. 1 déc. 2021 à 17:25, Ciaran Evans ***@***.***> a
écrit :

**Comment by ciaranevans** [comment]
Hey @dav1dc-pcf ! I've released the new version of `chaostoolkit-lib` https://pypi.org/project/chaostoolkit-lib/1.23.1/

If you run `pip install -U chaostoolkit-lib` that should update it for you 😄 If you could give it a go with the released version and then we can close this if you're happy!

**Comment by dav1dc-pcf** [comment]
It Werkz!! 😄

Two Thumbs Up and a Tonne of Thanks Folks!! 🙏

Keep up the Great Work. 😎

**Comment by ciaranevans** [comment]
Hooray! Glad to help!
