### ISSUE TITLE
os.path.join has separator before filename

### ISSUE THREAD

**Issue by pjn2work** [chaostoolkit/chaostoolkit#259]
https://github.com/chaostoolkit/chaostoolkit/blob/e34e610af88719ac51c2b1b0962801b44975d76a/setup.py#L12

You're doing an os.path.join (because of the OS separator) but already implying it by concatenating the sub-folder with the filename

So, it should be:
```
path = os.path.join(os.path.dirname(__file__), "chaostoolkit", "__init__.py")
```

**Comment by Lawouach** [comment]
Indeed! Good catch.
