### ISSUE TITLE
Variables from a .vars file

### ISSUE THREAD

**Issue by dhapola** [chaostoolkit/chaostoolkit#270]
**Is your feature request related to a problem? Please describe.**
At present, we have the option to maintain variables either in experiment file or set these in OS environment variables. These are not the most portable and version controllable. 

**Describe the solution you'd like**
For a particular environment, I would like to save variables in a text file and use it in multiple experiments. This would enable me maintain variables in git and reduce duplicity. Method would be similar to what we do in terraform by externalising variables from main script.

**Comment by Lawouach** [comment]
Hello.

Could this be the `--var-file` and `--vars` options from `chaos run`?

https://chaostoolkit.org/reference/usage/run/#override-configuration-and-secrets-at-runtime

**Comment by dhapola** [comment]
That should do. I will give it a shot. Thanks
