### ISSUE TITLE
Can't run chaos

### ISSUE THREAD

**Issue by Andrewkha** [chaostoolkit/chaostoolkit#287]
Hi!
Maybe I'm too stupid but...
I'm running Ubuntu 22.04 and Python 3.10.12

As instructed I have installed Chaos toolkit with `pip install -U chaostoolkit`
However if I try to check the version with `chaos --version` I get 

> Command 'chaos' not found, but can be installed with:
sudo apt install emboss

**Comment by Lawouach** [comment]
Hi @Andrewkha you are not doing anything stupid here.

However, it'd be interesting to know if the `pip install` command succeeded. Where you running this from a virtual environment?

**Comment by Andrewkha** [comment]
Hi @Lawouach !
When I do pip install it says `Defaulting to user installation because normal site-packages is not writeable`
I'm not running a virtual env since I'm experimenting this on my test VM and do not really care about potentinal versions conflicts.
I solved the issue adding the  /home/<username>/.local/ to PATH but not sure that's the correct way...

**Comment by Lawouach** [comment]
It is the right way indeed I believe.

**Comment by Andrewkha** [comment]
Thanks for the quick response and support @Lawouach
