### ISSUE TITLE
Python 3.12 can not install chaostoolkit-reporting successfully.

### ISSUE THREAD

**Issue by binbjz** [chaostoolkit/chaostoolkit#288]
**Describe the bug**
```sh
$ pip install -U chaostoolkit-reporting
......
  ERROR: Failed building wheel for pendulum
Failed to build pendulum
ERROR: Could not build wheels for pendulum, which is required to install pyproject.toml-based projects

Actually, chaostoolkit-reporting depends on maya, and maya depends on pendulum.
chaostoolkit-reporting==0.14.3
├── maya [required: Any, installed: 0.6.1]
│   ├── pendulum [required: >=2.0.2, installed: 2.1.2]
```

**Runtime versions**
Please run:

```
$ python --version
$ chaos info core
$ chaos info extensions
```

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Additional context**

**Comment by Lawouach** [comment]
Good catch. Thanks.

Python 3.12 has broken dependencies in many places. You probably need to report that [upstream](https://github.com/sdispater/pendulum). Maybe also look at https://github.com/sdispater/pendulum/issues/696 for ideas?

**Comment by binbjz** [comment]
It seems that Pendulum has a new version that now supports 3.12.

**Comment by Lawouach** [comment]
If you're successful, let me know, maybe we could pin it in the plugin at least.

**Comment by Lawouach** [comment]
Thanks. Does it fix the issue with the plugin?

**Comment by binbjz** [comment]
> Thanks. Does it fix the issue with the plugin?

I think it should have fixed this issue by now, but using the release version might be safer.

**Comment by binbjz** [comment]
The problem has been resolved.
