### ISSUE TITLE
chaos init should offer to create rollbacks actions

### ISSUE THREAD

**Issue by dviniere** [chaostoolkit/chaostoolkit#30]
I think that similarly to #28, it would be interesting that "chaos init" offer the possibility to generate the rollbacks action linked to the method done. 

For example, if I used a method "scale_microservice" to scale my application to 5, it would be nice to have in rollback at the end of the experiment that reverts it to my previous number of replica, so init would ask me to give me the opportunity to fill the "rollbacks", be it automatic with the discovery beforehand or manual with an input from user.

That would probably extend the current : 
""" [2018-01-30 16:50:27 INFO] Let's build a new experiment
Experiment's title: Experiment #1
Add an activity to your method """

by doing """
[2018-01-30 16:50:27 INFO] Let's build a new experiment
Experiment's title: Experiment #1
1)Add an activity to your method 
2)Add a steady-state hypothesis
3)Add an activity to your rollbacks  """

What do you guys think?

**Comment by Lawouach** [comment]
Sorry for the delay @dviniere. I think it's a good idea!
