### ISSUE TITLE
Broken katacoda.com link in the documentation

### ISSUE THREAD

**Issue by ppalsamy** [chaostoolkit/chaostoolkit#304]
**Describe the bug**
On this page: https://chaostoolkit.org/reference/usage/init/
In this text: A tutorial on how to use the chaos init command is available as part of the [Chaos Toolkit’s Getting Started tutorials.](https://www.katacoda.com/chaostoolkit/courses/01-chaostoolkit-getting-started)

same link is used few other places as well
`discover` - https://chaostoolkit.org/reference/usage/discover/
A tutorial on how to use the chaos discover command is available as part of the [Chaos Toolkit’s Getting Started tutorials.](https://www.katacoda.com/chaostoolkit/courses/01-chaostoolkit-getting-started)

 `run` - https://chaostoolkit.org/reference/usage/run/

A tutorial on how to use the chaos run command is available as part of the [Chaos Toolkit’s Getting Started tutorials.](https://www.katacoda.com/chaostoolkit/courses/01-chaostoolkit-getting-started)

 `report` -  https://chaostoolkit.org/reference/usage/report/
A tutorial on how to use the chaos report command is available as part of the [Chaos Toolkit’s Getting Started tutorials.](https://www.katacoda.com/chaostoolkit/courses/01-chaostoolkit-getting-started)

The link to katacoda.com is throwing 
404
Thank you to the Katacoda community for your years of support. Katacoda.com is now closed. Learn more about this decision and access interactive learning on O’Reilly [here](https://www.oreilly.com/online-learning/leveraging-katacoda-technology.html).

**To Reproduce**
Click  [Chaos Toolkit’s Getting Started tutorials.](https://www.katacoda.com/chaostoolkit/courses/01-chaostoolkit-getting-started)
on init reference page https://chaostoolkit.org/reference/usage/init/

**Comment by ppalsamy** [comment]
I can create PR if we have correct link

**Comment by Lawouach** [comment]
Hello @ppalsamy 

Thank you for the report. You are right, the links are invalid. But they cannot be fixed because Katacoda no longer exists. The best we can do so far is to entirely remove the links.

**Comment by ppalsamy** [comment]
Thanks @Lawouach, Is it ok to remove entire statement?

**Comment by Lawouach** [comment]
Very much so indeed.

**Comment by ppalsamy** [comment]
@Lawouach please check my PR

**Comment by Lawouach** [comment]
Indeed, that fixed it. Thanks!
