### ISSUE TITLE
Adding support for multiple environments

### ISSUE THREAD

**Issue by Sail0rd** [chaostoolkit/chaostoolkit#310]
**Is your feature request related to a problem? Please describe.**

I would love to have the same experiment (for example a stress experiment) work for multiple environment (preproduction, production, integration, ...) because there are only few things that changes between two environments (probe url, maybe some label, deployment name, ...)

**Describe the solution you'd like**

We could have an `environment.yaml` file that holds variables that will be changed/overriden according to the environment we want to target, e.g. a `chaos run --environment preprod experiment.yaml` would take all values in the preprod part of the environment.yaml and populate them in the experiment

**Describe alternatives you've considered**

For now I use only variables from environment variables with multiple .envrc and direnv to set the correct values according to the environment, but this imply to have one directory per environment and thus to duplicate all experiment in each  environment directory, which causes a code duplication i'd like to avoid

**Additional context**

What I currently have:
.
├── experiments
│   ├── preprod
│   │   ├── .envrc
│   │   ├── ingress-controller-pod-kill.yaml
│   │   ├── ingress-stress-cpu.yaml
│   │   ├── ingress-stress-memory.yaml
│   │   ├── io-stress.yaml
│   ├── prod
│   │   ├── .envrc
│   │   ├── ingress-controller-pod-kill.yaml
│   │   ├── ingress-stress-cpu.yaml
│   │   ├── ingress-stress-memory.yaml
│   │   ├── io-stress.yaml

what I'd like:
.
├── environments.yaml
├── experiments
│   ├── ingress-controller-pod-kill.yaml
│   ├── ingress-stress-cpu.yaml
│   ├── ingress-stress-memory.yaml
│   ├── io-stress.yaml

with an environment file that could look like this:

```yaml
preprod:
    url: preprod.app.com
    ...
prod:
    url: prod.app.com
```

**Comment by cdsre** [comment]
So my personal view on this is, you are on the right track with trying to reduce duplicate code and moving to a more DRY approach. Having a single set of experiments that can work for any env. Most of this will come from refactoring and utilising variables for the env specific values. 

I wouldnt put values for different envs in the same file. Instead I would have a `preprod_vars.yml` and a `prod_vars.yml`. that way you keep then isolated. It will also make them easier to track changes via version control like git.

CTK already provides a mechnism, for passing config at run time https://chaostoolkit.org/reference/usage/run/#override-configuration-and-secrets-at-runtime. so you could have something like 

**preprod_vars.yml**
```yaml
---
configuration:
  url: preprod.app.com
```

**prod_vars.yml**

```yaml
---
configuration:
  url: prod.app.com
```

Then when running your experiement assuming your code has been refactored to use the URL var. Then you can just switch out the file as needed. For example to run against preprod you would just run...

```bash
chaos run --var-file preprod_vars.yml
```

**Comment by Sail0rd** [comment]
That is exactly what I needed sorry for the issue, I didn't came across this page of the documentation before
