### ISSUE TITLE
Provide the docs for functions for actions

### ISSUE THREAD

**Issue by arun-gupta** [chaostoolkit/chaostoolkit#58]
The docs for different functions that can be used in actions would be very useful.

FYI @adrianco

**Comment by Lawouach** [comment]
I think this should be associated to https://github.com/chaostoolkit/chaostoolkit/pull/55 which started the same sort of work.

**Comment by Lawouach** [comment]
Driver extensions are now automatically generated documentation as well:

https://docs.chaostoolkit.org/drivers/overview/
