### ISSUE TITLE
New function to measure the number of replicas to serve concurrent users

### ISSUE THREAD

**Issue by arun-gupta** [chaostoolkit/chaostoolkit#59]
Provide a new function to measure the total time taken for execution of a test script. This will allow to measure if XXX concurrent user requests can be met with YYY replicas of a service.

FYI @adrianco

**Comment by Lawouach** [comment]
I'm going to close this issue because it feels it's more like a specific extension (say one dedicated to performance testing activities). It doesn't seem to be linked to the core.

Feel free to reach out @arun-gupta so we can discuss it further.
