### ISSUE TITLE
Add support for Rancher probes and actions

### ISSUE THREAD

**Issue by russmiles** [chaostoolkit/chaostoolkit#6]
As suggested by Bernd Dulfer (bernd.dulfer@t-systems.com) support for working with Rancher (http://rancher.com/docs/rancher/latest/en/) to probe and manipulate packaging, deployment and runtime management of Rancher containers. 

Kubernetes is the underlying support system, so the Kube support is already helpful, but there is more power in supporting fully what Rancher exposes.

**Comment by Lawouach** [comment]
Let's close this one until we really need it.
