### ISSUE TITLE
Consider adding a "test" mode to the toolkit, in addition to the default "experiment" mode

### ISSUE THREAD

**Issue by russmiles** [chaostoolkit/chaostoolkit#63]
I'd like to consider whether there _could_ be a "test" mode to the toolkit, where method execution failures result in different reporting etc. It's an interesting idea. At the moment the default mode is "experiment", i.e. we want the toolkit to act like we are focussed on discovering new information. "test" would affect the runtime reporting wholescale to support a focus on validation and verification of already-known facts.

**Comment by russmiles** [comment]
The rationale here is that I'm seeing Chaos Toolkit experiments go through a lifecycle where they start off as new-information-discovery experiments, and they then eventually mature into being part of a larger test-centric (i.e. validation and verification over discovery) picture once initial weaknesses have been discovered and overcome.

**Comment by 0rc** [comment]
I like the idea

**Comment by Lawouach** [comment]
See #57 as well.

**Comment by russmiles** [comment]
I think this is even more important when considering usage from CI, where a chaos experiment has eventually become a test in intention and is now part of a post-delivery CI/CD stage.
