### ISSUE TITLE
Add configure command

### ISSUE THREAD

**Issue by russmiles** [chaostoolkit/chaostoolkit#65]
A `configure` command allows the toolkit installation to manage its extensions (plugins and drivers) according to specific versions, and also to manipulate settings (stored in `~/.chaostoolkit/settings.yaml`).

The idea for the workflow is:
* `chaos configure -settings key:value key:value -plugins pluginName:1.0.0 pluginName:0.3.0 -drivers driverName driverName:0.4.0`
* "Would you like to create a new, local Python virtual environment for this configuration?"
* Yes ... new, fresh virtual environment, install it all including the toolkit itself.
* No ... continue...
* _If_ a collision in versions is detected in the current environment then...
* "You have specified driverName version 0.4.0, you already have version 0.2.1 installed, do you want to keep your current version (Y), or override with the configured version (O)?"

At the moment, `configure` cannot specify a version of the chaos toolkit itself. However it could do this in the future, particularly in the case where a new virtual environment is being specified.

Also, the choices in the above workflow could be defaulted with:
* `-virtualenv` to automatically create a local virtual environment
* `-override` to automatically override any version collisions, preferring the versions specified in the configure command.
* `--no-override` to prefer existing versions over those specified in the `configure` command, so ignoring any versions that are a collision with what is already present.

**Comment by Lawouach** [comment]
I'm going to prioritise this one as it helps automation.

**Comment by Lawouach** [comment]
But, for now, I will stick to implementing the command that sets keys in the settings file. I'm not sure yet about installing dependencies (a good idea but also a can of worms if not done well...)
