### ISSUE TITLE
Collaborator Promotion Process Call for Thoughts

### ISSUE THREAD

**Issue by russmiles** [chaostoolkit/chaostoolkit#75]
Currently we have a collection of open source projects and a wonderfully vibrant community around the Chaos Toolkit and the Incubator. As people from the community get involved, it becomes desirable that more responsibility for those projects is ideally subsumed by the community rather than the org owners (myself and @Lawouach currently).

I've like to propose that we collectively formulate a process whereby someone who everyone recognises is going beyond simple contribution to a project and in fact is becoming the trusted chaperone of the project can be "promoted" to have direct write access to `master` for that project.
 
The idea so far is to perhaps have something like the following:

1. Propose the promotion, who and to what repo, and reasoning as an issue on this repo.
2. Allow a sensible period for discussion for and against the proposal.
3. Final say to be made by the existing responsible project contributors.
4. Announcement and justification on the issue prior to it being closed and the new rights being allocated to the successfully promoted collaborator.

That's just my take so far though. This issue is a call out for ideas on what that process might be, so please add your own suggestions to this issue and then we can hopefully establish a V1 of our own community collaborator promotion process, which we'll add to the project documentation.

**Comment by nazarenof** [comment]
Hello,
sounds sensible, a few things to consider (as it is for core devs or kernel maintainers):
- a bug tracker / tt may be necessary, not sure if github issues would be enough.
- a mailing list for chaostk-devs and or chaostk-bugs.

ps. Please do not remove the peer review process.

**Comment by Lawouach** [comment]
Hey @nazarenof,

Could you describe scenarios that aren't met by GH issues? Segmenting our presence on various location isn't a good idea for the project's governance IMO.

As for the mailing-list, I appreciate the sentiment, though they would probably become slack channels instead of mailing-lists.

**Comment by nazarenof** [comment]
Certainly @Lawouach. 

I am used to Jira at work, which is on a different scale; GH issues are good for small sized projects, chaostoolkit at the moment, fits perfectly, but if you would like workflow tracking, or want to start creating/handling issues based on stage, version, components, GH will prove a challenge, you can use milestones I give you that.

For the mailing list, it has pros and cons, and yes, sometimes ML become slack channels, e.g. python mailing list, that is why people go to bug-trackers directly.

NB: As Russ pointed these suggestions are for the future, when you have several maintainers + people contributing as a one-time-thing.
