### ISSUE TITLE
Add Optional Contribution Model to Experiment Vocabulary and reporting

### ISSUE THREAD

**Issue by russmiles** [chaostoolkit/chaostoolkit#81]
I'd like a way to map the value that an experiment contributes so that it makes sense to technical and non-technical stakeholders in a system. When I conduct sessions to brainstorm and prioritise concerns to be explored using chaos engineering, this is mapped back to system properties that the business cares about along with an ascribed "weight" so that an experiment can declare what properties valuable to a business an experiment contributes to. I call this the Contribution Model, and I'd like to be able to introduce this as an optional section in an experiment's top-level description.

At the moment an experiment can have `version`, `title`, `description` and `tags` at this level:

```
{
    "version": "1.0.0",
    "title": "My application is resilient to admin-instigated node drainage",
    "description": "Can my application maintain its minimum resources?",
    "tags": [
        "service",
        "kubernetes"
    ],
```

I'd like to add another, optional, section similar to `tags` that describes the desirable system properties that the experiment contributes trust and confidence in, something like:

```
{
    "version": "1.0.0",
    "title": "My application is resilient to admin-instigated node drainage", 
    "description": "Can my application maintain its minimum resources?",
    "contributions": {  
            "reliability": "high",
            "security": "none",
            "scalability": "medium"
    }
    "tags": [
        "service",
        "kubernetes"
    ],
``` 

Initially I suggest that the following enumerations are supported:
* High - Maximum contribution to this valuable capability.
* Medium - Some contribution to this valuable capability.
* Low - Little contribution to this valuable capability.
* None - Explicitly declared as no contribution to this valuable capability.

**Comment by Lawouach** [comment]
This has been added to the spec and now handled by the reporting plugin. I believe this can be closed.
