### ISSUE TITLE
Won't build, "requirements-dev.txt" missing from package

### ISSUE THREAD

**Issue by claviola** [chaostoolkit/chaostoolkit#99]
When trying to install:

```
$ python setup.py
Traceback (most recent call last):
  File "setup.py", line 45, in <module>
    with io.open('requirements-dev.txt') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'requirements-dev.txt'
```

**Comment by Lawouach** [comment]
Hello,

Could you please explain which project that is from? Chaostoolkit right? (not one of the drivers I mean :))

I assyme you are running that command from a git clone?

**Comment by claviola** [comment]
Hi @Lawouach,

It's this one, yes. This issue is present both in the source that was uploaded to PyPI and the GH releases (looked at 0.17.1 and 1.0.0rc3).

**Comment by Lawouach** [comment]
Indeed. Good catch. I'll fix this today.
